</main>
<footer>
    <h2>Contacts :</h2>
    <p>Pour nous contacter ou effectuer des commandes vous pouvez nous écrire à : menestrel78280@gmail.com</p>
    <a href="http://a.pagnoux.free.fr/" rel="nofollow" id="realisateur">Ce site est réalisé par Anastassiya Pagnoux</a>
    <div id="goUp" class="none">
      <a href="#wrap"><i class="fa fa-bars"></i><i class="fa fa-chevron-circle-up"></i></a>
    </div>
</footer>
</div>
<script type="text/javascript" src="js/goUp.js"></script>
</body>
</html>
