<!DOCTYPE html>
<html lang="fr" >
  <head>
    <!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-141137047-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-141137047-1');
</script>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Artisanat-Ménestrel regroupe plusieurs savoir faire : créations en cuir, céramique, painture, cours de la langue russe." />
    <meta name="robots" content="index, follow" >
    <link rel="stylesheet" type="text/css" href="css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Amarante" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="css/style.css">
    <title>Artisanat-Ménestrel : Association artisanale et culturelle Franco-Russe à Tarbes</title>
  </head>
  <body>
    <div id="wrap">
      <header>
        <div class="conteiner">
          <img src="img/ornement-fleur.png" alt="Image de l'ornement fleurale">
				  <h1>Menestrel-Artisanat à Tarbes</h1>
          <p>Bijoux en cuir, décorations en céramique, cours de russe, traductions russe-français</p>
			 </div>
      </header>
      <nav class="conteiner">
        <ul id="nav">
          <li><a href="#presentation">Présentation</a></li>
          <li><a href="#auteur">Auteur</a></li>
          <li><a href="#cuir">Créations en cuir</a></li>
          <li><a href="#ceramique">Céramique</a></li>
          <li><a href="#peinture">Peinture</a></li>
          <li><a href="#ateliers">Ateliers</a></li>
          <li><a href="#evenements">Evénements</a></li>
        </ul>
      </nav>
      <main>
